import type { Metadata } from "next";
import { FaHeart } from "react-icons/fa";
import { IoMdCalendar } from "react-icons/io";
import { IoWalletOutline } from "react-icons/io5";
import { CiPizza } from "react-icons/ci";
import { IoMdHome } from "react-icons/io";
export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <section className="  flex flex-row bg-slate-200 ">
            <div className=" w-18 rounded-r-3xl h-auto bg-red-400 ">
                <div className="h-1/5 hover:bg-slate-400  ml-3  mr-3 hover:rounded-lg flex ">
                    <div className="relative h-1/2 w-full flex place-content-center  my-auto ">
                        <IoMdHome className="text-4xl text-white  " />
                    </div>
                </div>
                <div className="h-1/5 hover:bg-slate-400  ml-3  mr-3 hover:rounded-lg flex ">
                    <div className="relative h-1/2 w-full flex place-content-center  my-auto ">
                        <CiPizza className="text-4xl text-white  " />
                    </div>
                </div>
                <div className="h-1/5 hover:bg-slate-400  ml-3  mr-3 hover:rounded-lg flex ">
                    <div className="relative h-1/2 w-full flex place-content-center  my-auto ">
                        <IoMdCalendar className="text-4xl text-white  " />
                    </div>
                </div>
                <div className="h-1/5 hover:bg-slate-400 ml-3  mr-3 hover:rounded-lg flex ">
                    <div className="relative h-1/2 w-full flex place-content-center  my-auto ">
                        <IoWalletOutline className="text-4xl text-white  " />
                    </div>
                </div>
                <div className="h-1/5 hover:bg-slate-400  ml-3  mr-3 hover:rounded-lg flex ">
                    <div className="relative h-1/2 w-full flex place-content-center  my-auto ">
                        <FaHeart className="text-4xl text-white  " />
                    </div>
                </div>
            </div>
            <div className="static w-[100px] h-full  bg-slate-200 flex-1">
                {children}
            </div>
        </section>
    );
}
